version: "2"
services:
  app:
    build: ./
    volumes:
      - "./:/app"
    links:
      - db
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password